#!/bin/sh

PYTHON="/home/sean/pleiades/plone-sites/p1/bin/python"
INSTANCE_HOME="/home/sean/pleiades/plone-sites/p1/zope-instance"
SOFTWARE_HOME="/home/sean/pleiades/plone-sites/p1/Zope-2.9.3/lib/python"
PYTHONPATH="$SOFTWARE_HOME"
PRODUCTPATH="$SOFTWARE_HOME/Products/GeographicEntityLite"
export PYTHONPATH INSTANCE_HOME SOFTWARE_HOME

echo "running coverage tests ..."
$PYTHON coverage.py -e
$PYTHON coverage.py -x runalltests.py
$PYTHON coverage.py -rm $PRODUCTPATH/*.py

