#!/bin/sh

PYTHON="/usr/bin/python"
INSTANCE_HOME="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/instance"
SOFTWARE_HOME="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/Zope-2.9.4/lib/python"
PYTHONPATH="$SOFTWARE_HOME"
PRODUCTPATH="$SOFTWARE_HOME/Products/GeographicEntityLite"
export PYTHONPATH INSTANCE_HOME SOFTWARE_HOME

echo "running coverage tests ..."
$PYTHON coverage.py -e
$PYTHON coverage.py -x runalltests.py
$PYTHON coverage.py -rm $PRODUCTPATH/*.py $PRODUCTPATH/content/*.py $PRODUCTPATH/Extensions/*.py $PRODUCTPATH/adapters/*.py

