#!/bin/sh

PYTHON="/usr/bin/python"
ZOPE_HOME="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/Zope-2.9.4"
INSTANCE_HOME="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/instance"
CONFIG_FILE="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/instance/etc/zope.conf"
SOFTWARE_HOME="/home/sean/Jobs/AWMC/Pleiades/plone-sites/pleiades-dev/Zope-2.9.4/lib/python"
PYTHONPATH="$SOFTWARE_HOME"
export PYTHONPATH INSTANCE_HOME SOFTWARE_HOME
"$PYTHON" runalltests.py

